# =================================================================
# theme globals
# =================================================================
remote_theme: minlearn/jekyll-theme-utmapp-remote
plugins:
- jekyll-remote-theme
#baseurl: "/onekeydevdesk"
sass:
  style: :compressed
exclude:
  - LICENSE
  - CNAME
collections:
  pages:
    output: true
    permalink: /:path/
markdown: kramdown

# =================================================================
# theme settings
# =================================================================
page_title                                : onekeydevdesk - Build and deploy your cloud hypervisor/desktop/disk with onekeystoke
ios_app_id                                : 
appstore_link                             : 
playstore_link                            : 
github_link                               : https://github.com/minlearn/onekeydevdesk
presskit_download_link                    : 
app_icon                                  : assets/appicon.png
app_name                                  : Onekeydevdesk
app_price                                 : Build and deploy your cloud hypervisor/desktop/disk with onekeystoke
app_description                           : onekeydevdesk is a composed implentmented OS towards the "all in one onekeystoke devdesk" theories. just type ` wget -qO- 1keydd.com/inst.sh | bash ` to begin.
enable_smart_app_banner                   : false
email_address                             : minlearn@shalol.com
facebook_username                         : 
instagram_username                        : 
twitter_username                          : minlearn_1keydd
github_username                           : minlearn/onekeydevdesk
discord_address                           : 
footer_message                            : 
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"
cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8
device_color                              : black
body_background_color                     : "#ffffff"
link_color                                : "#1d63ea"
app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"
feature_title_color                       : "#000000"
feature_text_color                        : "#666666"
feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"
social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"
footer_text_color                         : "#666666"
features                                  : 
  - title                                 : 1keydd inst.sh
    description                           : mirror self-contained,support customized machine models,targets,wgetdd and ncdd mode,support customized network configuration
    fontawesome_icon_name                 : microchip
  - title                                 : 1keydd transve
    description                           : transparent pve manager,bring the seamless exp bewteen local and remote virtual vm
    fontawesome_icon_name                 : microchip
  - title                                 : 1keydd dirdisk
    description                           : easy to use directlink cloudstorage generator
    fontawesome_icon_name                 : microchip
videos                                    : 
  - /intro/1keydevdeskwin.png
  - /intro/1keydevdeskdsm.jpg
  - /intro/1keydevdeskosx.png
